[package]
name = "bmap-tools-rs"
version = "0.1.0"
authors = ["x"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.3"
flate2 = "0.2.20"
